/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  entryPoints: [
    'src/Perennial/index.ts',
    'src/lib/markets/index.ts',
    'src/lib/vaults/index.ts',
    'src/lib/contracts.ts',
    'src/lib/operators.ts',
    'src/constants/contracts.ts',
    'src/constants/markets.ts',
    'src/constants/vaults.ts',
    'src/constants/units.ts',
    'src/utils/accumulatorUtils.ts',
    'src/utils/addressUtils.ts',
    'src/utils/arrayUtils.ts',
    'src/utils/big6Utils.ts',
    'src/utils/contractUtils.ts',
    'src/utils/fundingAndInterestUtils.ts',
    'src/utils/graphUtils.ts',
    'src/utils/multiinvoker.ts',
    'src/utils/payoffUtils.ts',
    'src/utils/positionUtils.ts',
    'src/utils/pythUtils.ts',
    'src/utils/timeUtils.ts',
  ],
  out: 'docs',
  internalModule: 'Definitions',
  plugin: 'typedoc-plugin-missing-exports',
}
